"use client";

import { useEffect, useState } from "react";

type AuditLog = {
  id: number;
  session_id: string;
  action: string;
  tool_name: string | null;
  arguments: any;
  result: any;
  approval_required: boolean;
  approved: boolean;
  created_at: string;
};

export default function Dashboard() {
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [loading, setLoading] = useState(true);

  async function loadAuditLogs() {
    try {
      const response = await fetch(
        "http://127.0.0.1:8000/api/audit?limit=100"
      );

      if (!response.ok) {
        throw new Error("Failed to load audit logs");
      }

      const data = await response.json();

      if (Array.isArray(data)) {
        setLogs(data);
      }
    } catch (error) {
      console.error(
        "Could not load audit logs:",
        error
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadAuditLogs();

    const interval = setInterval(
      loadAuditLogs,
      5000
    );

    return () => clearInterval(interval);
  }, []);

  function formatData(data: any) {
    if (
      data === null ||
      data === undefined
    ) {
      return "—";
    }

    try {
      return JSON.stringify(
        data,
        null,
        2
      );
    } catch {
      return String(data);
    }
  }

  function formatTime(
    timestamp: string
  ) {
    try {
      return new Date(
        timestamp
      ).toLocaleString();
    } catch {
      return timestamp;
    }
  }

  const toolCalls = logs.filter(
    (log) =>
      log.action === "TOOL_CALL"
  ).length;

  const toolResults = logs.filter(
    (log) =>
      log.action === "TOOL_RESULT"
  ).length;

  const successfulResults =
    logs.filter(
      (log) =>
        log.action ===
          "TOOL_RESULT" &&
        log.result?.success === true
    ).length;

  const failedResults =
    logs.filter(
      (log) =>
        log.action ===
          "TOOL_RESULT" &&
        log.result?.error
    ).length;

  return (
    <main className="min-h-screen bg-gray-50 p-6">

      <div className="max-w-7xl mx-auto">

        {/* Header */}

        <div className="flex items-center justify-between mb-8">

          <div>

            <h1 className="text-3xl font-bold text-gray-900">
              Merchant Dashboard
            </h1>

            <p className="text-gray-500 mt-1">
              AI commerce activity and audit trail
            </p>

          </div>

          <a
            href="/"
            className="px-4 py-2 bg-black text-white rounded-xl hover:bg-gray-800"
          >
            ← Customer View
          </a>

        </div>

        {/* Overview */}

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">

          <div className="bg-white border rounded-2xl p-5 shadow-sm">

            <p className="text-sm text-gray-500">
              Agent Tool Calls
            </p>

            <p className="text-3xl font-bold mt-2 text-gray-900">
              {toolCalls}
            </p>

          </div>

          <div className="bg-white border rounded-2xl p-5 shadow-sm">

            <p className="text-sm text-gray-500">
              Tool Results
            </p>

            <p className="text-3xl font-bold mt-2 text-gray-900">
              {toolResults}
            </p>

          </div>

          <div className="bg-white border rounded-2xl p-5 shadow-sm">

            <p className="text-sm text-gray-500">
              Successful Actions
            </p>

            <p className="text-3xl font-bold mt-2 text-green-600">
              {successfulResults}
            </p>

          </div>

          <div className="bg-white border rounded-2xl p-5 shadow-sm">

            <p className="text-sm text-gray-500">
              Failed Actions
            </p>

            <p className="text-3xl font-bold mt-2 text-red-600">
              {failedResults}
            </p>

          </div>

        </div>

        {/* Audit Trail */}

        <div className="bg-white border rounded-2xl shadow-sm overflow-hidden">

          <div className="px-6 py-5 border-b flex items-center justify-between">

            <div>

              <h2 className="text-xl font-bold text-gray-900">
                Agent Audit Trail
              </h2>

              <p className="text-sm text-gray-500 mt-1">
                Every tool invocation and result generated by the AI agent
              </p>

            </div>

            <button
              onClick={loadAuditLogs}
              className="px-4 py-2 border border-gray-300 rounded-xl text-sm font-medium hover:bg-gray-50"
            >
              Refresh
            </button>

          </div>

          {loading ? (

            <div className="p-10 text-center text-gray-500">
              Loading audit trail...
            </div>

          ) : logs.length === 0 ? (

            <div className="p-10 text-center text-gray-500">
              No agent activity yet.
            </div>

          ) : (

            <div className="divide-y">

              {logs.map(
                (log) => (

                  <div
                    key={log.id}
                    className="p-6"
                  >

                    {/* Event header */}

                    <div className="flex items-center justify-between gap-4">

                      <div className="flex items-center gap-3">

                        <span
                          className={`text-xs font-bold px-3 py-1 rounded-full ${
                            log.action ===
                            "TOOL_CALL"
                              ? "bg-blue-100 text-blue-700"
                              : "bg-green-100 text-green-700"
                          }`}
                        >
                          {log.action}
                        </span>

                        {log.tool_name && (

                          <span className="font-semibold text-gray-900">
                            {log.tool_name}
                          </span>

                        )}

                      </div>

                      <span className="text-xs text-gray-400">
                        {formatTime(
                          log.created_at
                        )}
                      </span>

                    </div>

                    {/* Event details */}

                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-4">

                      <div>

                        <p className="text-xs font-semibold text-gray-500 mb-2">
                          Arguments
                        </p>

                        <pre className="bg-gray-50 border rounded-xl p-4 text-xs text-gray-700 overflow-x-auto">
                          {formatData(
                            log.arguments
                          )}
                        </pre>

                      </div>

                      <div>

                        <p className="text-xs font-semibold text-gray-500 mb-2">
                          Result
                        </p>

                        <pre className="bg-gray-50 border rounded-xl p-4 text-xs text-gray-700 overflow-x-auto">
                          {formatData(
                            log.result
                          )}
                        </pre>

                      </div>

                    </div>

                    {/* Approval */}

                    {log.approval_required && (

                      <div className="mt-4 flex items-center gap-3">

                        <span className="text-sm font-medium text-gray-600">
                          Payment approval:
                        </span>

                        <span
                          className={`text-xs font-bold px-3 py-1 rounded-full ${
                            log.approved
                              ? "bg-green-100 text-green-700"
                              : "bg-yellow-100 text-yellow-700"
                          }`}
                        >
                          {log.approved
                            ? "✓ APPROVED"
                            : "NOT APPROVED"}
                        </span>

                      </div>

                    )}

                  </div>

                )
              )}

            </div>

          )}

        </div>

      </div>

    </main>
  );
}